Repository stephin007/Cowin-Vaccine-Availablity-Checker, pull requests merged in 2021-05, with the labels that each got.

#29 Added new UI for the each Vaccine Data.
  src/components/Home/Home.css
  src/components/Home/Home.js
  src/components/VaccineData/SingleVaccineData/VaccineDataSingle.css
  src/components/VaccineData/SingleVaccineData/VaccineDataSingle.js
Labels: enhancement

#31 Added custom Time badges
  src/components/VaccineData/SingleVaccineData/VaccineDataSingle.css
  src/components/VaccineData/SingleVaccineData/VaccineDataSingle.js
Labels: enhancement

#37 Enhanced vaccine card UI
  src/components/VaccineData/SingleVaccineData/VaccineDataSingle.css
  src/components/VaccineData/SingleVaccineData/VaccineDataSingle.js
Labels: enhancement

#41 Finalized vaccine card UI
  src/components/VaccineData/SingleVaccineData/VaccineDataSingle.css
  src/components/VaccineData/SingleVaccineData/VaccineDataSingle.js
Labels: enhancement

#49 Revamped the Whole NewUI
  README.md
  src/components/Home/Home.css
  src/components/Home/Home.js
Labels: enhancement, good first issue

#51 New UI fixes
  src/components/Home/Home.css
  src/components/Home/Home.js
  src/components/VaccineData/SingleVaccineData/VaccineDataSingle.js
  src/components/VaccineData/VaccineDataMain.js
Labels: BugFIix, enhancement, good first issue

#60 Emptied the array when searchvalues changes
  src/components/Home/Home.js
  src/components/VaccineData/VaccineDataMain.js
Labels: enhancement

#73 Vaccine Card Design
  src/components/VaccineData/SingleVaccineData/VaccineDataSingle.css
  src/components/VaccineData/SingleVaccineData/VaccineDataSingle.js
Labels: enhancement

#80 Vaccine card enhancement
  src/components/Home/Home.js
  src/components/VaccineData/SingleVaccineData/VaccineDataSingle.js
Labels: bug, enhancement

#95 Staging merge to master for Prod Release
  README.md
  package.json
  src/App.js
  src/components/About/About.css
  src/components/About/About.js
  src/components/Header/Header.css
  src/components/Header/Header.js
  src/components/Home/Home.css
  src/components/Home/Home.js
  src/components/Main.css
  src/components/Main.js
  src/components/VaccineData/SingleVaccineData/VaccineDataSingle.css
  src/components/VaccineData/SingleVaccineData/VaccineDataSingle.js
  src/components/VaccineData/VaccineDataMain.js
  yarn.lock
Labels: Release

#105 docs: fix broken link
  README.md
Labels: BugFIix, enhancement

#100 feat: add map to each result-card
  .env.example
  .gitignore
  package.json
  src/components/Home/Home.js
  src/components/VaccineData/Map/index.js
  src/components/VaccineData/SingleVaccineData/VaccineDataSingle.css
  src/components/VaccineData/SingleVaccineData/VaccineDataSingle.js
  src/index.css
  src/index.js
  yarn.lock
Labels: enhancement, good first issue, help wanted, new feature

#120 edited .env.example
  .env.example
  .github/PULL_REQUEST_TEMPLATE.md
Labels: bug, documentation

#127 About Page Revamp
  src/components/About/About.css
  src/components/About/About.js
Labels: enhancement, good first issue
