Repository stephin007/Cowin-Vaccine-Availablity-Checker, pull requests merged in 2021-06, with the labels that each got.

#129 ABOUT PAGE REVAMP
  src/components/About/About.css
  src/components/About/About.js
Labels: documentation, enhancement, good first issue

#134 Added extra information about the project to the About Page
  src/components/About/About.css
  src/components/About/About.js
  src/components/globalStyles.js
Labels: documentation, enhancement, good first issue

#89 Added Null State Component in NEW-UI
  src/components/Error.js
  src/components/Home/Home.js
  src/components/NullState.js
  src/images/noData.png
  yarn.lock
Labels: bug

#135 Added a loading component - Feat/issue 97
  .gitignore
  src/components/Home/Home.js
  src/components/VaccineData/VaccineDataMain.js
Labels: enhancement

#136 Fixed wrong URL being passed for git profiles
  src/components/About/About.js
Labels: BugFIix, bug, enhancement

#138 fixed loading issue
  src/components/Home/Home.js
  src/components/NullState.js
  src/components/VaccineData/VaccineDataMain.js
Labels: BugFIix, bug

#141 Height Issues in the contributors section of about page fixed
  src/components/About/About.css
  src/components/About/About.js
Labels: BugFIix, documentation, enhancement, good first issue

#145 Feature: Add Whole world Vaccine Information
  src/App.js
  src/components/CovidInfo/CovidIndia.js/CovidIndia.js
  src/components/CovidInfo/CovidInfoMain.js
  src/components/CovidInfo/CovidWorld.js/CovidWorld.css
  src/components/CovidInfo/CovidWorld.js/CovidWorld.js
  src/components/Header/Header.js
Labels: enhancement, good first issue, help wanted, new feature

#149 Enhancement: Enhanced the look for word COVID Info
  src/components/CovidInfo/CovidWorld.js/CovidWorld.css
  src/components/CovidInfo/CovidWorld.js/CovidWorld.js
  src/components/CovidInfo/CovidWorld.js/CovidWorldContents.js
Labels: enhancement, good first issue

#153 Feature: Add Test Cases
  .gitignore
  CONTRIBUTING.md
  package.json
  src/__tests__/__snapshots__/about.js.snap
  src/__tests__/__snapshots__/covidInfoMain.js.snap
  src/__tests__/__snapshots__/header.js.snap
  src/__tests__/__snapshots__/home.js.snap
  src/__tests__/__snapshots__/intro.js.snap
  src/__tests__/about.js
  src/__tests__/covidInfoMain.js
  src/__tests__/header.js
  src/__tests__/home.js
  src/__tests__/intro.js
  src/components/CovidInfo/CovidInfoMain.js
  src/components/Header/Header.js
  src/components/Home/Home.js
  src/setupTests.js
  yarn.lock
Labels: documentation, enhancement

#156 Removed pagination from default branch
  src/components/Home/Home.js
  src/components/Pagination/Pagination.css
  src/components/Pagination/Pagination.js
  yarn.lock
Labels: BugFIix

#157 Merge to Staging
  .env.example
  .github/CONTRIBUTING.md
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/codeql-analysis.yml
  .gitignore
  .idea/.gitignore
  .idea/Cowin-Vaccine-Availablity-Checker.iml
  .idea/modules.xml
  .idea/vcs.xml
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  README.md
  package.json
  src/App.js
  src/__tests__/__snapshots__/about.js.snap
  src/__tests__/__snapshots__/covidInfoMain.js.snap
  src/__tests__/__snapshots__/header.js.snap
  src/__tests__/__snapshots__/home.js.snap
  src/__tests__/__snapshots__/intro.js.snap
  src/__tests__/about.js
  src/__tests__/covidInfoMain.js
  src/__tests__/header.js
  src/__tests__/home.js
  src/__tests__/intro.js
  src/components/About/About.css
  src/components/About/About.js
  src/components/CovidInfo/CovidIndia.js/CovidIndia.js
  src/components/CovidInfo/CovidInfoMain.js
  src/components/CovidInfo/CovidWorld.js/CovidWorld.css
  src/components/CovidInfo/CovidWorld.js/CovidWorld.js
  src/components/CovidInfo/CovidWorld.js/CovidWorldContents.js
  src/components/Error.js
  src/components/Header/Header.css
  src/components/Header/Header.js
  src/components/Header/HeaderStyles.js
  src/components/Home/Home.css
  src/components/Home/Home.js
  src/components/Intro/Intro.css
  src/components/Intro/Intro.js
  src/components/Main.js
  src/components/NullState.js
  src/components/VaccineData/Map/index.js
  src/components/VaccineData/SingleVaccineData/VaccineDataSingle.css
  src/components/VaccineData/SingleVaccineData/VaccineDataSingle.js
  src/components/VaccineData/VaccineDataMain.js
  src/components/globalStyles.js
  src/components/themes.js
  src/components/useDarkMode.js
  src/images/noData.png
  src/index.css
  src/index.js
  src/setupTests.js
  yarn.lock
Labels: Release

#162 Removed Style - Components
  package.json
Labels: dependancy

#167 restructured the Charts file to the Worldcovid parent folder
  src/components/Chart.js
  src/components/ContinentChart.js
  src/components/CovidInfo/CovidWorld.js/CovidWorld.js
  src/components/CovidInfo/CovidWorld.js/CovidWorldContents.js
Labels: documentation

#169 Enhancement/issue 166
  src/components/Home/Home.js
Labels: enhancement, good first issue, new feature

#170 STAGING DEPLOYMENT 16/06/2021
  package.json
  public/index.html
  src/App.js
  src/components/About/About.css
  src/components/About/About.js
  src/components/CovidInfo/CovidWorld.js/CovidWorld.js
  src/components/CovidInfo/CovidWorld.js/CovidWorldContents.js
  src/components/Home/Home.js
  yarn.lock
Labels: Release

#172 PRODUCTION DEPLOYMENT
  .env.example
  .github/CONTRIBUTING.md
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/codeql-analysis.yml
  .gitignore
  .idea/.gitignore
  .idea/Cowin-Vaccine-Availablity-Checker.iml
  .idea/modules.xml
  .idea/vcs.xml
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  README.md
  package.json
  public/index.html
  src/App.js
  src/__tests__/__snapshots__/about.js.snap
  src/__tests__/__snapshots__/covidInfoMain.js.snap
  src/__tests__/__snapshots__/header.js.snap
  src/__tests__/__snapshots__/home.js.snap
  src/__tests__/__snapshots__/intro.js.snap
  src/__tests__/about.js
  src/__tests__/covidInfoMain.js
  src/__tests__/header.js
  src/__tests__/home.js
  src/__tests__/intro.js
  src/components/About/About.css
  src/components/About/About.js
  src/components/CovidInfo/CovidIndia.js/CovidIndia.js
  src/components/CovidInfo/CovidInfoMain.js
  src/components/CovidInfo/CovidWorld.js/CovidWorld.css
  src/components/CovidInfo/CovidWorld.js/CovidWorld.js
  src/components/CovidInfo/CovidWorld.js/CovidWorldContents.js
  src/components/Error.js
  src/components/Header/Header.css
  src/components/Header/Header.js
  src/components/Header/HeaderStyles.js
  src/components/Home/Home.css
  src/components/Home/Home.js
  src/components/Intro/Intro.css
  src/components/Intro/Intro.js
  src/components/Main.js
  src/components/NullState.js
  src/components/VaccineData/Map/index.js
  src/components/VaccineData/SingleVaccineData/VaccineDataSingle.css
  src/components/VaccineData/SingleVaccineData/VaccineDataSingle.js
  src/components/VaccineData/VaccineDataMain.js
  src/components/globalStyles.js
  src/components/themes.js
  src/components/useDarkMode.js
  src/images/noData.png
  src/index.css
  src/index.js
  src/setupTests.js
  yarn.lock
Labels: Release

#171 Added 3rd option in the World Covid Info.
  src/App.css
  src/components/CovidInfo/CovidWorld.js/CovidWorld.css
  src/components/CovidInfo/CovidWorld.js/CovidWorld.js
  src/components/CovidInfo/CovidWorld.js/CovidWorldContents.js
Labels: enhancement, good first issue, new feature

#174 🚨 STAGING DEPLOYMENT 🚨
  src/App.css
  src/components/About/About.css
  src/components/CovidInfo/CovidWorld.js/CovidWorld.css
  src/components/CovidInfo/CovidWorld.js/CovidWorld.js
  src/components/CovidInfo/CovidWorld.js/CovidWorldContents.js
Labels: Release

#173 added conflicts workflow
  .github/workflows/conflicts.yml
Labels: CodeChange

#175 Added the 3rd option for showing per country covid data
  src/components/CovidInfo/CovidWorld.js/CovidWorld.css
  src/components/CovidInfo/CovidWorld.js/CovidWorld.js
  src/components/CovidInfo/CovidWorld.js/CovidWorldContents.js
Labels: enhancement, good first issue, help wanted, new feature, up-for-grabs

#177 🚨 STAGING DEPLOYMENT🚨
  .github/workflows/conflicts.yml
  src/components/CovidInfo/CovidWorld.js/CovidWorld.css
  src/components/CovidInfo/CovidWorld.js/CovidWorld.js
  src/components/CovidInfo/CovidWorld.js/CovidWorldContents.js
Labels: Release
